# Generated by Django 4.1.4 on 2023-01-05 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_game_id_alter_game_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='spread',
            new_name='away_spread',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away', to='app.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_spread',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home', to='app.team'),
            preserve_default=False,
        ),
    ]
